### ISSUE TITLE
real one page app

### ISSUE THREAD

**Issue by andreas83** [andreas83/SocialNetwork#67]
While developing the new group feature it turned out, that
extending and modifying the existing react structure is extremely inflexible and complex. 
in my opinion the main reason is, the missing controller and routing component. 
on the long run we should rewrite the structure and add at least some sort of routing
also i need a clean solution for communication between components aka controller. 

i really like to address this issue on the next refactoring release, 
in the meantime please don't hesitate and make code and or feature suggestions.

**Comment by chilimatic** [comment]
react is still not a framework just a view :) just take a full framework :)

**Comment by andreas83** [comment]
@chilimatic thanks for pointing out, did not thought about that before. :walking:

**Comment by chilimatic** [comment]
well you stated the obvious :)

**Comment by andreas83** [comment]
please let me know if you have any recommendation or like to share some thoughts about 
angular, redux, flux (insert your awesome js framework here)

when it comes to a rewrite, i would love to drop bootstrap and jquery, since they are to heavy in my opinion. also adding webpack could be an option. 

maybe we can discuss this later, do you have some spare time ?

**Comment by chilimatic** [comment]
hmm afaik redux contains flux and is kind of a state container for react. And Flux is mainly an observer system for unidirectional event propagation. or in not so fancy terms ... it controls the events :D 

I like cycle.js but it's reactive and functional so this can be confusing. I would, since you want drive a product not, how you often put it, "reinvent the wheel". go with ember or angular those will provide the biggest amount of prepared plugins and just just have to integrate them. 

I just fear for some things you won't get rid of bootstrap and jquery unless you want to reinvent the wheel :)

**Comment by andreas83** [comment]
jquery can be replaced  with zeptojs since is mostly feature complete but much much faster and lighter.

**Comment by andreas83** [comment]
i may have to correct myself...
http://zurb.com/article/1293/why-we-dropped-zepto

**Comment by neuron303** [comment]
but is zeptojs web scale?

**Comment by andreas83** [comment]
If /dev/null is fast in web scale I will use it!

**Comment by andreas83** [comment]
i will close this issue and open another one, since this conversation went to an completely wrong direction ...
