### ISSUE TITLE
Must be in root directory?

### ISSUE THREAD

**Issue by ThaMunsta** [andreas83/SocialNetwork#83]
Does this have to be hosted in the root directory? I'm trying to run this on Windows Server 2012 PHP 5.2. Everything seems to work but the paths are all relative to the main website not the subfolder I have the files in. The address configuration doesn't seem to do much. Am I missing something?

**Comment by andreas83** [comment]
mhm you could try to add following to the head 
`<head><base href="/subfolder/"></head>`

but never tested it so far.

**Comment by ThaMunsta** [comment]
It looks like that could work but all of the relative paths have a \ which ignores that tag. I tested removing it with the CSS line and it worked.
Doesn't work:
`<link rel="stylesheet" href="/public/css/style.min.css">`
Works:
`<link rel="stylesheet" href="public/css/style.min.css">`
I'll try going through the code and changing those. Thanks!

**Comment by ThaMunsta** [comment]
Oh, except every page is being treated as a 404 because it's not ignoring the sub directory when it looks at the url. Is there a way to get it to look at the url "subfolder/user/register/" as just "user/register/" ?

**Comment by chilimatic** [comment]
the easy dirty way would be modifying the content of $_SERVER['REQUEST_URI'] variable before the routing is triggered.
I would recommend the beginning of the init.php script

a clean solution would have to be implemented but you maybe don't want to wait for that :)

another one would be adding the url to the routing with a define('URL_PREFIX', '/blub') and append it to routing in routing.php as prefix.

**Comment by ThaMunsta** [comment]
Doing a str_replace on $_SERVER['REQUEST_URI'] to remove the subfolder seems to work for the most part but I need to fix some links still for things like user registration and I'm not sure about login if that will work.

URL_PREFIX trick I don't think I understand enough about the routing to get working. My subfolder is "wall" so I tried adding define('URL_PREFIX', '/wall'); but it didn't seem to do much.

This is a good learning experience so I'll keep tinkering with it but I really appreciate the help. Also just found the /backend/ part and jeez is that ever awesome. Fantastic work on this guys! I'm loving it :D

**Comment by chilimatic** [comment]
I see, well it's a rather straight forward architecture which is good if you're not used to such systems.

It seams like didn't explain enough for the URL_PREFIX first of all ;D my mistake it should be the the URI_PREFIX -

> > Unique Resource Identifier

 because it's a specific **resource** we route to.


`
$router->map('GET|POST', URL_PREFIX.'/user/login/', '\SocialNetwork\app\controller\UserController#login');
`

so if the prefix is empty -> it will be /user/login/ but if it's set it will prepend the other string/path to be mapped :)

this is a more inversive change but it's more correct than changing the $_SERVER variable because you shouldn't modify it in general since it's a super global and mutations of superglobals are really hard to track "who/what modified $_SERVER['blub'] when" this is debugging hell ;D ....

i hope this helps a little

**Comment by ThaMunsta** [comment]
Helps a lot actually thank you. I have almost everything working now. Just need to change a few redirect URLs still. I have registration and logging in working. Just need to get sharing working and some smaller bits. Thanks so much!

**Comment by andreas83** [comment]
You are welcome :+1: 
If you need any further advice, don't hesitate to ask
